apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-credentials
type: Opaque
data:
  admin-user: {{ randAlphaNum 8 | b64enc | quote }}
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}