# Default values for smarter-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: example.com

cert-manager:
  nodeSelector:
    demo: terminal
  ingressShim:
    defaultIssuerGroup: cert-manager.io
    defaultIssuerKind: ClusterIssuer
    defaultIssuerName: self-signed-issuer

fluent-bit:
  secret: notsecret
  nodeSelector:
    demo: terminal
  image:
    tag: 2.0.3
  service:
    type: NodePort
  extraPorts:
    - name: in-forward
      containerPort: 24224
      port: 24224
      protocol: TCP
      nodePort: 30224

  config:
    inputs: |
      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              24224
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   6M
      [INPUT]
          name          cpu
          Tag           cpu
          Interval_Sec  30
    filters: |
      # No Filters

    outputs: |
      [OUTPUT]
          Name          stdout
          Match         * 
      [OUTPUT]
          Name          influxdb
          Match         *
          Host          {{ .Release.Name }}-influxdb-0
          Port          8086
          Database      waggledemo
          Sequence_Tag  _seq
          Tag_Keys      method path
          tls           Off
            
influxdb:
  nodeSelector:
    demo: terminal
  service:
    type: NodePort
    nodePorts:
      http: 32086
  image:
    tag: "1.8"
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 4Gi

  initScripts:
    enabled: true
    scripts:
      init.iql: |+
        CREATE DATABASE "waggledemo"; CREATE DATABASE "prometheus";CREATE DATABASE "waggle"

prometheus:
  nodeSelector:
    demo: terminal
  grafana:
  #  service:
  #    type: NodePort
  #    nodePorts:
  #      http: 32080
    nodeSelector:
      demo: terminal
    adminPassword: notsecret
    persistence:
      enabled: true
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 3Gi
    extraVolumeMounts:
      - name: image0
        mountPath: /mnt
        readOnly: true
        hostPath: /tmp
    additionalDataSources:
      - name: InfluxDB-Waggle 
        type: influxdb
        url: http://{{ .Release.Name }}-influxdb-0:8086
        access: proxy
        isDefault: false
        database: "waggledemo"
        basicAuth: false
        readonly: false
      - name: InfluxDB-internal
        type: influxdb
        url: http://{{ .Release.Name }}-influxdb-0:8086
        access: proxy
        isDefault: false
        database: "_internal"
        basicAuth: false
        readonly: false  
  prometheus:
    nodeSelector:
      demo: terminal
    prometheusSpec:
      ## The remote_read spec configuration for Prometheus.
      ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#remotereadspec
      # remoteRead: 
      #   - url: "http://influxdb:8086/api/v1/prom/read?db=prometheus"

      ## The remote_write spec configuration for Prometheus.
      ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#remotewritespec
      # remoteWrite: 
      #   - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 3Gi
